openapi: 3.0.0
info:
  title: Employees
  version: "1.0"
servers: []
paths:
  "/employees":
    patch:
      summary: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeDetails"
      responses:
        "200":
          description: Employee Created Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Employee:
      type: object
      required:
        - id
        - employeeCode
        - name
        - department
        - designation
      properties:
        id:
          type: integer
        employeeCode:
          type: string
        name:
          type: string
        department:
          type: string
        designation:
          type: string

    EmployeeDetails:
      type: object
      required:
        - name
        - employeeCode
      properties:
        name:
          type: string
        employeeCode:
          type: string
