name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check API Contracts
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Get changed yaml files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            io/**/*.yaml
            io/**/*.yml
            io/**/*.json
          files_ignore: kafka.yaml

      - name: Create environment file
        run: |
            # echo "GITHUB_REF=${{ github.ref }}" >> env.list
            echo "GITHUB_SHA=${{ github.sha }}" >> env.list
            echo "GITHUB_REPOSITORY=${{ github.repository }}" >> env.list
            echo "GITHUB_ACTOR=${{ github.actor }}" >> env.list
            echo "GITHUB_WORKFLOW=${{ github.workflow }}" >> env.list
            echo "GITHUB_HEAD_REF=${{ github.head_ref }}" >> env.list
            if [ -z "${{ github.base_ref }}" ]; then
                echo "GITHUB_BASE_REF=${{ github.ref }}" | sed 's/refs\/heads\///' >> env.list
            else
              echo "GITHUB_BASE_REF=${{ github.base_ref }}" >> env.list
            fi     

      - name: Validate OpenAPI examples
        run: |
          docker run -v "$(pwd):/repo:rw" \
            --env-file env.list \
            znsio/specmatic-openapi examples validate --specs-dir=/repo/io/specmatic/examples/store/openapi

